apiVersion: apps/v1
kind: Deployment
metadata:
  name: shape-color-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shape-color-app
  template:
    metadata:
      labels:
        app: shape-color-app
    spec:
      containers:
        - name: backend
          image: krish141/kindergarden-app-backend
          ports:
            - containerPort: 5000
        - name: frontend
          image: krish141/kindergarden-app-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shape-color-service
spec:
  selector:
    app: shape-color-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30008
  type: NodePort      
