name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t krish141/kindergarden-app-backend:latest ./backend
          docker push krish141/kindergarden-app-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t krish141/kindergarden-app-frontend:latest ./frontend
          docker push krish141/kindergarden-app-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config get-contexts
          kubectl config current-context

      - name: Debug - List Files
        run: ls -R

      - name: Debug - Check k8s Directory
        run: ls -R k8s/    

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml

