name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t your-dockerhub-username/shape-color-backend:latest ./backend
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push krish141/shape-color-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t your-dockerhub-username/shape-color-frontend:latest ./frontend
          docker push krish141/shape-color-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
